### ISSUE TITLE
scp_config.yaml duplicate information as in configuration.yaml?

### ISSUE THREAD

**Issue by MyYo** [SpaceHummus/flight-software#5]
Does scp_config.yaml (https://github.com/SpaceHummus/flight-software/blob/main/scp_conf.yaml) define the folder to upload files? What is the difference between scp_config.yaml and configuration.yaml folder_id field (https://github.com/SpaceHummus/interfaces/blob/main/configuration.yaml)

**Comment by razst** [comment]
folder_id removed from configuration.yaml
